name = "ea-license-system"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "ea_license_db_new"
database_name = "ea-license-db-new"
database_id = "7f5b4848-aa34-4640-b039-4ea0d28663fc"

[vars]
PLACEHOLDER = "placeholder"