name = "ea-license-system"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "ea_license_db_new"
database_name = "ea-license-db-new"
database_id = "7f5b4848-aa34-4640-b039-4ea0d28663fc"

[vars]
ENABLE_MULTI_TENANCY = "1"
DEFAULT_TENANT_ID    = "tenant_default"

# Paystack Configuration
PAYSTACK_PUBLIC_KEY = "pk_test_fdf6e6165d336131eb791fb05b39b6e5050a1564"
PAYSTACK_SECRET_KEY = "sk_test_64083826ab32a72dcdf031d83797dc250adf94f7"

# Other optional settings
BILLING_CALLBACK_URL = "https://dashboard.ghwmelite.work/billing/success"
ENFORCE_BILLING = "1"
TELEGRAM_CHAT_ID = "-1002902266828"
ALERT_DIGEST_LOOKBACK_HOURS = "24"

[triggers]
crons = ["0 2 * * *"]